- name: install openvpn
  yum: name=openvpn-2.3.12 state=present

- name: unzip RemoteMaintenance.zip
  unarchive:
    src: RemoteMaintenance.zip
    dest: /home/

- name: exec manage.py
  shell: chdir=/home/RemoteMaintenance/ nohup python manage.py runserver 0.0.0.0:8800 &

- name: add RemoteMaintenance into /etc/rc.d/rc.local
  lineinfile:
    dest: /etc/rc.d/rc.local
    line: "{{ item }}"
    state: present
  with_items:
    - cd /home/RemoteMaintenance/; nohup python manage.py runserver 0.0.0.0:8800 &
